### ISSUE TITLE
Incorrect "latest version" information for Rails in Gemfile.lock table

### ISSUE THREAD

**Issue by tomnatt** [librariesio/support#101] opened 2016-08-17 11:34 UTC
Rails and many related Action\* and Active\* gems are reporting the incorrect latest versions. 

For example here:
https://libraries.io/github/tomnatt/show-tell

I am seeing latest stable Rails as 3.2.22.4.

**Comment by andrew** [comment] 2016-12-14 16:34
I'm going to close this as a duplicate of https://github.com/librariesio/libraries.io/issues/337

**Closed by andrew** 2016-12-14 16:34 UTC
Labels: bug
